from .client import Client
from .inquiry import Inquiry
from .conversation import Conversation
from .requirement import Requirement
from .department import Department
from .employee import Employee
from .skill import Skill
from .employee_skill import EmployeeSkill
from .employee_availability import EmployeeAvailability
from .technology import Technology
from .infrastructure import Infrastructure
from .completed_project import CompletedProject
from .project_qualification import ProjectQualification
from .manager_notification import ManagerNotification